App_auth/urls.py
from django.urls import path
from App_auth import views

app_name = "App_auth"

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.signup_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
]

App_main/urls.py
from django.urls import path
from App_main import views

app_name = "App_main"

urlpatterns = [
    path('', views.home, name='home'),
    path('boss-dashboard', views.boss_dashboard, name='boss-dashboard'),
    path('employee-dashboard', views.employee_dashboard, name='employee-dashboard'),
    path('boss-view-all-employees', views.boss_view_of_all_employees, name='boss-view-all-employees'),
    path('boss-view-task-manager', views.boss_view_task_manager, name='boss-view-task-manager'),
    path('boss-assign-new-task/', views.boss_assign_new_task, name='boss-assign-new-task'),
    path('boss-add-new-employee/', views.boss_add_new_employee, name='boss-add-new-employee'),
    path('boss-employee-signup/', views.boss_employee_signup, name='boss-employee-signup'),
    path('boss-employee-profile-setup/', views.boss_employee_profile_setup, name='boss-employee-profile-setup'),

    # Employees
    path('employee-dashboard/', views.employee_dashboard, name='employee-dashboard'),
    path('employee-new-task/', views.employee_new_task, name='employee-new-task'),
    path('employee-task-status-change/<int:pk>/<str:status>/', views.employee_change_task_changer,
         name='employee-task-status-change'),
    path('employee-completed-task/', views.employee_completed_task, name='employee-completed-task'),
    path('employee-running-task/', views.employee_running_task, name='employee-running-task'),
]

etmp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_main.urls')),
    path('auth/', include('App_auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_main/models.py
from django.db import models
from App_auth.models import User

# Create your models here.
t_status = (
    ('Assigned', 'Assigned'),
    ('Pending', 'Pending'),
    ('Started', 'Started'),
    ('Completed', 'Completed'),
)


class ProjectModel(models.Model):
    task_name = models.CharField(max_length=150)
    work_overview = models.TextField(blank=True)
    work_file = models.FileField(blank=True, null=True, upload_to='TaskFile/')
    assigned_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='assigned_by')
    assigned_to = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='assigned_to')
    deadline = models.DateTimeField(blank=True, null=True)
    task_status = models.CharField(max_length=50, choices=t_status)

    def __str__(self):
        return f"{self.task_name}-{self.deadline}"

App_main/forms.py
from django import forms
from App_main.models import *


class ProjectModelForm(forms.ModelForm):
    deadline = forms.CharField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = ProjectModel
        exclude = ['assigned_by', 'task_status']

App_main/views.py
from django.http import HttpResponse
from django.shortcuts import render, HttpResponseRedirect, reverse, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test

from App_auth.forms import EmployeeProfileModelForm
from App_auth.views import *
from App_auth.models import *
from App_main.models import *
from App_main.forms import ProjectModelForm


# Create your views here.
def home(request):
    if is_boss(request.user):
        return HttpResponseRedirect(reverse('App_main:boss-dashboard'))
    elif is_employee(request.user):
        return HttpResponseRedirect(reverse('App_main:employee-dashboard'))
    return HttpResponseRedirect(reverse('App_auth:login'))


@login_required
@user_passes_test(is_boss)
def boss_dashboard(request):
    total_employee = EmployeeProfileModel.objects.all().count()
    total_jobs = ProjectModel.objects.all().count()
    total_jobs_running = ProjectModel.objects.filter(task_status='Pending').count()
    content = {
        'total_employee': total_employee,
        'total_jobs': total_jobs,
        'total_jobs_running': total_jobs_running
    }
    return render(request, 'App_main/boss/boss_dashboard.html', context=content)


@login_required
@user_passes_test(is_boss)
def boss_view_of_all_employees(request):
    all_employee = EmployeeProfileModel.objects.all()
    content = {
        'all_employee': all_employee
    }
    return render(request, 'App_main/boss/all_employees.html', context=content)


@login_required
@user_passes_test(is_boss)
def boss_view_task_manager(request):
    tasks = ProjectModel.objects.all()
    taskForm = ProjectModelForm()
    content = {
        'tasks': tasks,
        'taskForm': taskForm,
    }
    return render(request, 'App_main/boss/boss_task_manager.html', context=content)


def boss_assign_new_task(request):
    if request.method == 'POST':
        taskForm = ProjectModelForm(request.POST, request.FILES)
        if taskForm.is_valid():
            thisForm = taskForm.save(commit=False)
            thisForm.assigned_by = request.user
            thisForm.task_status = 'Assigned'
            thisForm.save()
            return HttpResponseRedirect(reverse('App_main:boss-view-task-manager'))

    return redirect('App_main:boss-dashboard')


def boss_add_new_employee(request):
    employeeSignUpForm = SignUpForm()
    employeeProfileForm = EmployeeProfileModelForm()
    content = {
        'signupForm': employeeSignUpForm,
        'employeeProfileForm': employeeProfileForm,
    }

    return render(request, 'App_main/boss/boss_added_new_employee.html', context=content)


def boss_employee_signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            my_admin_group = Group.objects.get_or_create(name='Employee')
            my_admin_group[0].user_set.add(user)
            return HttpResponseRedirect(reverse('App_main:boss-employee-signup'))
    return HttpResponseRedirect(reverse('App_main:home'))


def boss_employee_profile_setup(request):
    if request.method == 'POST':
        form = EmployeeProfileModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_main:boss-employee-signup'))
    return HttpResponseRedirect(reverse('App_main:home'))


def employee_dashboard(request):
    total_pending_task = ProjectModel.objects.filter(task_status='Assigned')
    total_started_task = ProjectModel.objects.filter(task_status='Pending')
    total_running_task = ProjectModel.objects.filter(task_status='Started')
    total_Completed_task = ProjectModel.objects.filter(task_status='Completed')
    content = {
        'total_pending_task': total_pending_task,
        'total_started_task': total_started_task,
        'total_running_task': total_running_task,
        'total_Completed_task': total_Completed_task
    }
    return render(request, 'App_main/employee/employee_dashboard.html', context=content)


def employee_new_task(request):
    new_tasks = ProjectModel.objects.filter(task_status='Assigned')
    content = {
        'new_tasks': new_tasks
    }
    return render(request, 'App_main/employee/employee_new_task.html', context=content)


def employee_completed_task(request):
    com_tasks = ProjectModel.objects.filter(task_status='Completed')
    content = {
        'com_tasks': com_tasks,
    }
    return render(request, 'App_main/employee/employee_completed_task.html', context=content)


def employee_running_task(request):
    run_tasks = ProjectModel.objects.filter(task_status='Started')
    content = {
        'run_tasks': run_tasks,
    }
    return render(request, 'App_main/employee/employee_running_task.html', context=content)



def employee_change_task_changer(request, pk, status):
    task = ProjectModel.objects.get(id=pk)
    task.task_status = status
    task.save()
    return HttpResponseRedirect(reverse('App_main:employee-new-task'))

templates/App_main/boss/all_employees.html
{% extends 'App_main/boss/boss_dashboard.html' %}
{% block title %}

{% endblock %}
{% block main %}

{% endblock %}

templates/App_main/boss/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/App_main/common.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Marcellus&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <title>Employee Task Manager | {% block title %}

    {% endblock %}</title>
</head>
<body>
<div class="container">
    <div class="navigation">
        <ul>
            <li>
                <a href="#">
                    <span class="icon">
                        <img src="{% static 'images/Pathao-icon(1).png' %}" alt="Logo" width="100" height="70">
                    </span>
                    <span class="title">
                        Brand Name
                    </span>
                </a>
            </li>
            <li>
                <a href="{% url 'App_main:boss-dashboard' %}">
                    <span class="icon">
                        <ion-icon name="home-outline"></ion-icon>
                    </span>
                    <span class="title">
                        Dashboard
                    </span>
                </a>
            </li>
            <li>
                <a href="{% url 'App_main:boss-view-all-employees' %}">
                    <span class="icon">
                        <ion-icon name="person-outline"></ion-icon>
                    </span>
                    <span class="title">
                        Employees
                    </span>
                </a>
            </li>
            <li>
                <a href="{% url 'App_main:boss-view-task-manager' %}">
                    <span class="icon">
                        <ion-icon name="bag-outline"></ion-icon>
                    </span>
                    <span class="title">
                        Tasks
                    </span>
                </a>
            </li>
            <li>
                <a href="{% url 'App_main:boss-add-new-employee' %}">
                    <span class="icon">
                        <ion-icon name="person-add-outline"></ion-icon>
                    </span>
                    <span class="title">
                        Add New Employee
                    </span>
                </a>
            </li>
            <li>
                <a href="#">
                    <span class="icon">
                        <ion-icon name="settings"></ion-icon>
                    </span>
                    <span class="title">
                        Settings
                    </span>
                </a>
            </li>
            <li>
                <a href="{% url 'App_auth:logout' %}">
                    <span class="icon">
                        <ion-icon name="log-out"></ion-icon>
                    </span>
                    <span class="title">
                        Sign out
                    </span>
                </a>
            </li>
        </ul>
    </div>
</div>
<div class="main">
    <div class="topbar">
        <div class="toggle">
            <ion-icon name="grid-outline"></ion-icon>
        </div>
        <!-- Search -->
        <div class="search">
            <label>
                <input type="text" placeholder="Search Here">
                <ion-icon name="search-outline"></ion-icon>
            </label>
        </div>
        <!-- User Image -->
        <div class="user">
            <img src="{% static 'images/Pathao-icon.png' %}" alt="{{ request.user.email }}">
        </div>
    </div>
    {% block main %}

    {% endblock %}
</div>
<script>
    let dashboard = document.getElementById('id-');
    let toggle = document.querySelector('.toggle');
    let navigation = document.querySelector('.navigation');
    let main = document.querySelector('.main');


    toggle.addEventListener('click', () => {
        navigation.classList.toggle('active');
        main.classList.toggle('active');
    })
</script>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>
</html>

templates/App_main/boss/boss_added_new_employee.html
{% extends 'App_main/boss/boss_dashboard.html' %}
{% load static %}
{% block title %}
    New Employee Adder
{% endblock %}
{% block main %}
    <link rel="stylesheet" href="{% static 'css/App_main/boss/add-new-employee.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <div class="all-container">
        <div class="form-container" id="id-signup-form-container">
            <form id="id-signupForm" action="{% url 'App_main:boss-employee-signup' %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <legend>
                    Add new Employee
                </legend>
                <fieldset>
                    {{ signupForm.as_p }}
                </fieldset>
                <div class="submission-btn-container">
                    <button type="submit" class="btn btn-done btn-md">Submit</button>
                </div>
            </form>
        </div>
        <div class="form-container" id="id-profile-form-container">
            <form id="id-employee-profileForm" action="{% url 'App_main:boss-employee-profile-setup' %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <legend>
                    Create new Employee Profile
                </legend>
                <fieldset>
                    {{ employeeProfileForm.as_p }}
                </fieldset>
                <div class="submission-btn-container">
                    <button type="submit" class="btn btn-done btn-md">Submit</button>
                </div>
            </form>
        </div>
    </div>

    {#    <script>#}
    {#        $(document).on('submit', '#id-signupForm', function (e) {#}
    {#            e.preventDefault();#}
    {#            $.ajax({#}
    {#                type: 'Post',#}
    {#                url: '/boss-employee-signup/',#}
    {#                data: {#}
    {#                    email: $('id_email').val(),#}
    {#                    password1: $('id_password1'),#}
    {#                    password2: $('id_password2'),#}
    {#                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),#}
    {#                },#}
    {#                success: function (data) {#}
    {#                    Swal.fire(#}
    {#                        'Congratulations!',#}
    {#                        data,#}
    {#                        'success'#}
    {#                    )#}
    {#                }#}
    {#            })#}
    {#        });#}
    {#    </script>#}

    <script>
        let inputs = document.getElementsByTagName('input');
        for (const input of inputs) {
            input.classList.add('input-controller');
        }
    </script>
{% endblock %}

templates/App_main/boss/boss_dashboard.html
{% extends 'App_main/boss/base.html' %}
{% load static %}
{% block title %}

{% endblock %}
{% block main %}
    <link rel="stylesheet" href="{% static 'css/App_main/boss/boss_dashboard.css' %}">
    <div class="cardBox">
        <div class="card">
            <div>
                <div class="numbers">{{ total_employee }}</div>
                <div class="cardName">
                    Total Employees
                </div>
            </div>
            <div class="iconBx">
                <ion-icon name="people-outline"></ion-icon>
            </div>
        </div>
        <div class="card">
            <div>
                <div class="numbers">{{ total_jobs }}</div>
                <div class="cardName">
                    Total Jobs
                </div>
            </div>
            <div class="iconBx">
                <ion-icon name="bag-outline"></ion-icon>
            </div>
        </div>
        <div class="card">
            <div>
                <div class="numbers">{{ total_jobs_running }}</div>
                <div class="cardName">
                    Total Job Running
                </div>
            </div>
            <div class="iconBx">
                <ion-icon name="qr-code-outline"></ion-icon>
            </div>
        </div>
    </div>
{% endblock %}

templates/App_main/boss/boss_task_manager.html
{% extends 'App_main/boss/boss_dashboard.html' %}
{% load static %}
{% block title %}
    Task Manager
{% endblock %}
{% block main %}
    <link rel="stylesheet" href="{% static 'css/App_main/boss/boss_task_manager.css' %}">
    <div class="all-container">
        <div class="container" id="id-task-table-container">
            <table id="id-task-table">
                <h2 class="table-caption">Task List</h2>
                <div class="search-container">
                    <button class="btn btn-done btn-md" onclick="FilterKeyWord('Completed')">
                        Completed
                    </button>
                    <button class="btn btn-waiting btn-md" onclick="FilterKeyWord('Pending')">
                        Pending
                    </button>
                    <button class="btn btn-primary btn-md" onclick="FilterKeyWord('Assigned')">
                        Assigned
                    </button>
                    <button class="btn btn-new btn-big" onclick="assignNewTask(1)">Assign New Task</button>
                </div>
                <thead>
                <tr>
                    <th scope="col">Task Name</th>
                    <th scope="col">Assigned to</th>
                    <th scope="col">Task Overview</th>
                    <th scope="col">Status</th>
                    <th scope="col">Deadline</th>
                </tr>
                </thead>
                <tbody>
                {% if tasks %}
                    {% for task in tasks %}
                        <tr>
                            <td data-label="Task Name">{{ task.task_name }}</td>
                            <td data-label="Assigned to">{{ task.assigned_to }}</td>
                            <td data-label="Task Overview">{{ task.work_overview }}</td>
                            <td data-label="Status">{{ task.task_status }}</td>
                            {% if task.deadline %}
                                <td data-label="Deadline">{{ task.deadline.date }}</td>
                            {% else %}
                                <td data-label="Dateline">
                                    Not Mentioned
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                {% else %}
                    <td data-label="Task Name">
                        <ion-icon name="cloud-offline-outline"></ion-icon>
                    </td>
                    <td data-label="Assigned to">
                        <ion-icon name="cloud-offline-outline"></ion-icon>
                    </td>
                    <td data-label="Task Overview">
                        <ion-icon name="cloud-offline-outline"></ion-icon>
                    </td>
                    <td data-label="Status">
                        <ion-icon name="cloud-offline-outline"></ion-icon>
                    </td>
                    <td data-label="Dateline">
                        <ion-icon name="cloud-offline-outline"></ion-icon>
                    </td>
                {% endif %}
                </tbody>
            </table>
        </div>
        <div class="form-container" id="id-assign-new-task-container">
            <form action="{% url 'App_main:boss-assign-new-task' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <legend>
                    Assign New Task
                </legend>
                <fieldset>
                    <button type="button" class="btn btn-disclose btn-new btn-md" onclick="assignNewTask(0)">
                        X
                    </button>
                    {{ taskForm.as_p }}
                </fieldset>
                <div class="submission-btn-container">
                    <button type="submit" class="btn btn-done btn-md">Submit</button>
                    <button class="btn btn-disclose btn-md" type="button" onclick="assignNewTask(0)">Close</button>
                </div>
            </form>
        </div>
    </div>

    <script>
        let inputs = document.getElementsByTagName('input');
        for (const input of inputs) {
            input.classList.add('input-controller');
        }

        const assignNewTask = (value) => {
            let taskTable = document.getElementById('id-task-table-container');
            let newTaskForm = document.getElementById('id-assign-new-task-container');
            if (value === 0) {
                taskTable.style.display = 'block';
                newTaskForm.style.display = 'none';
            }
            else if (value === 1) {
                taskTable.style.display = 'none';
                newTaskForm.style.display = 'block';
            }
        }

        const FilterKeyWord = (searchInput) => {
            // Declare variables
            let input, filter, table, tr, td, i;
            input = searchInput;
            filter = input.toLowerCase();
            table = document.getElementById("id-task-table");
            tr = table.getElementsByTagName("tr");

            // Loop through all table rows, and hide those who don't match the search query
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[3];
                // change index to change your column search

                if (td) {
                    if (td.innerHTML.toLowerCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>
{% endblock %}